name = "my-email-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "example.com"
ADMIN_ACCOUNT = "admin"

[[kv_namespaces]]
binding = "EMAIL"
id = "你的id"

[[kv_namespaces]]
binding = "EMAIL_USER"
id = "你的id"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "attachments"

[build]
  [[build.upload.rules]]
  type = "Text"
  globs = ["**/*.html"]
